### ISSUE TITLE
Run "nightly build/docker job" just for original repo, not forks 

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#338]
https://github.com/actions/runner/issues/859

`if: github.repository == 'OpenHausIO/backend'`

```yml
name: Publish Docker nightly image

on:
    push:
        branches: [dev]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.repository == 'OpenHausIO/backend'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build  
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: openhaus/backend
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:  openhaus/backend:nightly
          labels: ${{ steps.meta.outputs.labels }}
```
