### ISSUE TITLE
Update workflow file & verions

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#434]
The github workflow files show warnings that node v16 is deprecated.
Update the actions versions, see: https://github.com/OpenHausIO/backend/issues/430

```yml
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

env:
    VAULT_MASTER_PASSWORD: Pa$$w0rd

jobs:
    build:
        #runs-on: [ubuntu-18.04, ubuntu-latest]
        runs-on: ${{ matrix.os }}

        # httpbin for helper/request
        services:
            httpbin:
                image: kennethreitz/httpbin
                ports: 
                    - 80:80

        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [16.x, 17.x, 18.x]           # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
                mongodb-version: ["4.2", "4.4", "5.0"]

        steps:
            - uses: actions/checkout@v2

            # mongodb setup
            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.7.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}            

            # node.js setup
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run build --if-present
            - run: npm run lint
            - run: npm test
    
```

**Comment by mStirner** [comment]
Update .yml file breaks the runner?

```yml
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

env:
    VAULT_MASTER_PASSWORD: Pa$$w0rd

jobs:
    build:
        #runs-on: [ubuntu-18.04, ubuntu-latest]
        runs-on: ${{ matrix.os }}

        # httpbin for helper/request
        services:
            httpbin:
                image: kennethreitz/httpbin
                ports: 
                    - 80:80

        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [18.x, 20.x]            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
                mongodb-version: ["4.2", "4.4", "5.0"]

        steps:
            - uses: actions/checkout@v2

            # mongodb setup
            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.7.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}            

            # node.js setup
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run build --if-present
            - run: npm run lint
            - run: npm test
```

The check `npm run test` does not finishes and times out:
![grafik](https://github.com/OpenHausIO/backend/assets/5003424/c538b914-a6db-469f-a072-8e086e1941d3)
![grafik](https://github.com/OpenHausIO/backend/assets/5003424/11780121-3096-4b25-a3a4-e4f82fea82d0)
