### ISSUE TITLE
Automate releases (GitHub actions)

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#88]
A quick test with github actions to release new version was semi successful.
Release a build & created, but the are error with tagging & body content.

`./github/workflows/release.yml`:

```yml
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
    build:
        #runs-on: [ubuntu-18.04, ubuntu-latest]
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2     

            - name: get-npm-version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@master

            # node.js setup
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            # run npm commands
            - run: npm install
            - run: npm run build:dist
            - run: grunt compress
            
            # create changelog
            - name: Changelog
              uses: scottbrenner/generate-changelog-action@master
              id: Changelog
              env:
                REPO: ${{ github.repository }}

            # create release
            - name: release
              uses: actions/create-release@v1
              id: create_release
              with:
                draft: false
                prerelease: false
                release_name: backend-v${{steps.package-version.outputs.current-version}}
                tag_name: foo21ea13
                body: "Test release"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload attachment
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ github.token }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: backend-v${{steps.package-version.outputs.current-version}}.tgz
                asset_name: backend-v${{steps.package-version.outputs.current-version}}.tgz
                asset_content_type: application/gzip

#            - name: Attach *.tgz file
#              uses: actions/upload-artifact@v3
#              with:
#                path: backend-v${{steps.package-version.outputs.current-version}}.tgz
```

[`actions/create-release@v1`](https://github.com/actions/create-release) is not maintained any more.
When you use `${{ github.ref }}` for the `tag_name` field following error occurs: `{"resource":"Release","code":"already_exists","field":"tag_name"}`
